Repository ArjunSharda/Searchor, pull requests merged in 2022-09, with the labels that each got.

#13 V1.2.0
  Code/CHANGELOG.txt
  Code/Searchor/__init__.py
  Code/setup.py
Labels: enhancement, Priority: Major

#14 Added: Target, Genius, Twitch and StackOverflow to the search functions.
  Code/Searchor/__init__.py
Labels: enhancement, Priority: Minor

#17 v1.3.0
  Code/CHANGELOG.txt
  Code/Searchor/__init__.py
Labels: enhancement, Priority: Major

#18 New Websites.
  Code/Searchor/__init__.py
Labels: enhancement, Priority: Minor

#21 Revert "New Websites."
  Code/Searchor/__init__.py
Labels: enhancement, Priority: Major

#23 V1.4.0
  Code/CHANGELOG.txt
  Code/Searchor/__init__.py
  Code/setup.py
Labels: enhancement, Priority: Major

#25 fix typo on import library
  README.md
Labels: documentation, enhancement, Priority: Minor

#27 Auto Pypi Uploads.
  .github/workflows/python-publish.yml
  .gitignore
  CHANGELOG.txt
  README.md
  ext/Searchor.png
  pyproject.toml
  src/MANIFEST.in
  src/setup.py
Labels: enhancement, Priority: High

#28 Update pyproject.toml
  pyproject.toml
Labels: enhancement, Priority: High

#29 uncapitalise imports
  .github/CODEOWNERS
  CHANGELOG.txt
  README.md
  examples/custom.py
  examples/searchamazon.py
  examples/searchbing.py
  examples/searchduckduckgo.py
  examples/searchgoogle.py
  examples/searchwikipedia.py
  examples/searchyahoo.py
  pyproject.toml
Labels: enhancement, Priority: Minor

#32 readmefix & uncapitalise
  ext/searchor.png
  pyproject.toml
  src/searchor/__init__.py
Labels: enhancement, Priority: Low

#34 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement, Priority: Minor

#36 CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, Priority: Minor

#40 Order engines by alphabetical order
  src/searchor/__init__.py
Labels: enhancement, Priority: Medium

#38 added view engine list function
  README.md
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor

#41 V2.1.0
  src/searchor/__init__.py
Labels: enhancement, Priority: Medium

#42 Fixed url to src
  LEARN.md
Labels: documentation, enhancement, Priority: Minor

#43 added pull request template
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement, Priority: Minor

#50 Change PULL_REQUEST_TEMPLATE.md wording
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement, Priority: Medium
