Repository ArjunSharda/Searchor, pull requests merged in 2022-10, with the labels that each got.

#60 Update Learn.MD wording
  LEARN.md
Labels: documentation, enhancement, Priority: Minor

#59 Added few search engine to __init__.py
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#53 add contributing.md
  CONTRIBUTING.md
Labels: enhancement, Priority: Low

#57 Added FedEx search queries function
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#52 G2 search queries function added
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#58 Added PyPi Search Query
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#54 Added Ebay Search query #47
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#66 Feature/usps search query
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#62 added ups query
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#67 added instructions
  README.md
  src/searchor/__init__.py
Labels: documentation, enhancement, Priority: Minor, hacktoberfest

#68 Added medium search query
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#71 Add changelog for v2.1.2
  README.md
Labels: enhancement, Priority: High

#72 added Spotify search function
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#80 Add Reddit Search
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#77 Add AWS search + change link for AOL
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#75 Add Altassian search
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#81 docs(CODE_OF_CONDUCT.md) Change software team leader to "collaborator"
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, Priority: Minor, hacktoberfest

#83 Amend incorrect Engine names
  src/searchor/__init__.py
Labels: bug, Priority: Medium, hacktoberfest

#84 Added BlogSpot Search query
  examples/custom.py
  examples/searchamazon.py
  examples/searchbing.py
  examples/searchduckduckgo.py
  examples/searchgoogle.py
  examples/searchwikipedia.py
  examples/searchyahoo.py
  src/searchor/__init__.py
Labels: enhancement, Priority: Medium, hacktoberfest

#87 Add discord button to README.md
  README.md
Labels: documentation, enhancement, Priority: Minor, hacktoberfest, no-code

#73 More search queries m9m
  src/searchor/__init__.py
Labels: enhancement, Priority: Low, hacktoberfest

#86 Open URL in the browser
  src/searchor/__init__.py
Labels: enhancement, Priority: Low, hacktoberfest

#92 V2.2.0
  README.md
  examples/open_web.py
  examples/searchamazon.py
  examples/searchbing.py
  examples/searchduckduckgo.py
  examples/searchgoogle.py
  examples/searchwikipedia.py
  examples/searchyahoo.py
  pyproject.toml
  src/searchor/__init__.py
Labels: enhancement, Priority: Major, hacktoberfest

#90 Added GitLab search query
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#102 added instagram, brave and alternativeto search engines
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#96 #95 Added Docker Hub search Query Engine
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#104 Added unsplash search engine
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#99 Add google maps and images query
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#98 Add: more query search engines
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#109 v2.2.1
  README.md
  pyproject.toml
  src/searchor/__init__.py
Labels: enhancement, Priority: High, hacktoberfest

#106 Copy URL to clipboard
  NOTICE.md
  examples/copy_url.py
  src/searchor/__init__.py
Labels: enhancement, Priority: Medium, hacktoberfest

#108 Contributors Section and Socalify added
  README.md
Labels: documentation, enhancement, Priority: Minor, hacktoberfest

#110 Adding Askubuntu and playstore
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#114 Added new engines
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#113 Added new engines
  README.md
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#111 Add and Rearrange engines
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#115 v2.2.3
  src/searchor/__init__.py
Labels: enhancement, Priority: High, hacktoberfest

#117 added extra search engines
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#118 Searchor cli
  setup.py
  src/searchor/main.py
Labels: enhancement, Priority: Major, hacktoberfest

#123 added reuters search query
  README.md
  src/searchor/__init__.py
Labels: enhancement, Priority: Minor, hacktoberfest

#122 added functionality to add custom search engines
  NOTICE.md
  examples/custom_engine.py
  setup.py
  src/searchor/__init__.py
Labels: enhancement, Priority: High, hacktoberfest

#125 Add history command to searchor cli
  src/searchor/__init__.py
  src/searchor/history.py
  src/searchor/main.py
Labels: enhancement, Priority: Medium, hacktoberfest

#126 Fixed unclear example in SUPPORTED_OPTIONS.md
  examples/cli/SUPPORTED_OPTIONS.md
Labels: enhancement, Priority: Minor, hacktoberfest

#127 2.4.0
  NOTICE.md
  README.md
  examples/cli/SUPPORTED_OPTIONS.md
  examples/custom_engine.py
  pyproject.toml
  setup.py
  src/searchor/__init__.py
  src/searchor/history.py
  src/searchor/main.py
Labels: documentation, enhancement, Priority: Major, hacktoberfest

#129 Fixed comments in bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement, Priority: Minor, hacktoberfest

#131 ci: Cache pip dependencies
  .github/workflows/python-publish.yml
Labels: enhancement, Priority: Minor, hacktoberfest

#130 removed eval from search cli method
  src/searchor/main.py
Labels: enhancement, Priority: Medium, hacktoberfest

#134 Introduce docker
  .dockerignore
  Dockerfile
Labels: enhancement, Priority: Medium, hacktoberfest
